---
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

name: bash

jobs:
  shellcheck:
    name: Test Bash Scripts
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.36  # we need prove
    steps:
      - uses: actions/checkout@v3
      - name: install Bats
        run: >
          cd /tmp &&
          git clone https://github.com/bats-core/bats-core.git --depth 1 &&
          cd bats-core &&
          ./install.sh /usr/local
      - name: Install Minilla
        run: cpm install -g Minilla
      - name: Configure git
        run: >
          git config --global user.email "foo@example.com" &&
          git config --global user.name "Min Illa"
      - name: bats tests
        run: bats -v && bats t
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
          COVERALLS_TOKEN: ${{secrets.COVERALLS_TOKEN}}
